### PR TITLE
add link in cart to redirect to products if cart is empty

### PR DESCRIPTION
**Pull request by DuiNotDoy**
I've added link in the cart page for redirecting users to products page when their cart is empty.

### CODE REVIEW

**Comment by nikohoffren** [comment]
> I've added link in the cart page for redirecting users to products page when their cart is empty.

Looks good but can you also add some hover effect to it, i can merge it after that.

**Review by nikohoffren — CHANGES_REQUESTED** [review]
Looks good but can you also add some hover effect to it, i can merge it after that.

**Comment by DuiNotDoy** [comment]
I'm having some problems with the hover effect, some effects work like text color and shadows but others don't. Other classes also doesn't seem to work like outline and background colors (it works when you I use the 500 variant though).

**Comment by nikohoffren** [comment]
> I'm having some problems with the hover effect, some effects work like text color and shadows but others don't. Other classes also doesn't seem to work like outline and background colors (it works when you I use the 500 variant though).

Okay, no problem. I can add them myself later. I merge this in now.

**Pull request merged**
